name: sistema_tickets_edis
description: Sistema de tickets TI con flujos RM/FG y reportes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  drift: ^2.14.1
  drift_dev: ^2.14.1
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.2
  path: ^1.8.3
  uuid: ^4.2.1
  collection: ^1.18.0
  equatable: ^2.0.5
  pdf: ^3.10.8
  csv: ^5.0.2
  fl_chart: ^0.66.2
  flutter_local_notifications: ^17.1.2
  intl: ^0.18.1
  timezone: ^0.9.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  # Azure AD + Dataverse
  flutter_appauth: ^6.0.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  drift_dev: ^2.14.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/catalogs/
